/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author ren
 */
public class FrameMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMenu.class.getName());

    /**
     * Creates new form FrameMenu
     */
    
    private String role;
    
    public FrameMenu(String role) {
        initComponents();
        this.role = role;
        applyRoleAccess();
    }
    
    private void applyRoleAccess() {
    if (role == null) return;

    if (role.equalsIgnoreCase("OFFICER")) {
        menuClient.setEnabled(false);
        menuPackage.setEnabled(false);

        btnClient.setEnabled(false);
        btnPackage.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnClient = new javax.swing.JButton();
        btnPackage = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbMaster = new javax.swing.JMenu();
        menuClient = new javax.swing.JMenuItem();
        menuPackage = new javax.swing.JMenuItem();
        menuPayments = new javax.swing.JMenuItem();
        mbClose = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PMB ");

        jToolBar1.setForeground(new java.awt.Color(0, 0, 255));
        jToolBar1.setRollover(true);

        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer-service (1).png"))); // NOI18N
        btnClient.setFocusable(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClient);

        btnPackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attached-file (1).png"))); // NOI18N
        btnPackage.setFocusable(false);
        btnPackage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPackage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPackage);

        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contract (1).png"))); // NOI18N
        btnPayment.setFocusable(false);
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPayment);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out (1).png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/i_had_seen_the_same_dream_again__by_loundraw_d9tw12o-fullview (1) (1).jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 255));

        mbMaster.setForeground(new java.awt.Color(255, 255, 255));
        mbMaster.setText("Master Data");

        menuClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuClient.setText("Manage Client");
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });
        mbMaster.add(menuClient);

        menuPackage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPackage.setText("Manage Package");
        menuPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPackageActionPerformed(evt);
            }
        });
        mbMaster.add(menuPackage);

        menuPayments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPayments.setText("Payments");
        menuPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaymentsActionPerformed(evt);
            }
        });
        mbMaster.add(menuPayments);

        jMenuBar1.add(mbMaster);

        mbClose.setForeground(new java.awt.Color(255, 255, 255));
        mbClose.setText("Close");

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        mbClose.add(menuExit);

        jMenuBar1.add(mbClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed
        // TODO add your handling code here:
        new FrameClient().setVisible(true);
    }//GEN-LAST:event_menuClientActionPerformed

    private void menuPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPackageActionPerformed
        // TODO add your handling code here:
        new FramePackage().setVisible(true);
    }//GEN-LAST:event_menuPackageActionPerformed

    private void btnPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageActionPerformed
        // TODO add your handling code here:
        new FramePackage().setVisible(true);
    }//GEN-LAST:event_btnPackageActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        new FramePayment().setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaymentsActionPerformed
        // TODO add your handling code here:
        new FramePayment().setVisible(true);
    }//GEN-LAST:event_menuPaymentsActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        // TODO add your handling code here:
        new FrameClient().setVisible(true);
    }//GEN-LAST:event_btnClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPackage;
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mbClose;
    private javax.swing.JMenu mbMaster;
    private javax.swing.JMenuItem menuClient;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuPackage;
    private javax.swing.JMenuItem menuPayments;
    // End of variables declaration//GEN-END:variables
}
